### ISSUE TITLE
The search bar at the top right doesn't work

### ISSUE THREAD

**Issue by Abilityguy** [mlpack/mlpack.org#33]
#### Problem location

https://www.mlpack.org/doc/mlpack-git/doxygen/tutorials.html
The problem persists in other pages of the documentation too.

![Screenshot](https://user-images.githubusercontent.com/33577829/94011763-80d44100-fdc5-11ea-9982-80591623da59.png)

#### Description of problem

The search bar at the top right of the documentation doesn't work.
I have tried pressing the 'Enter' key and clicking on the icon but nothing happens.

Upon inspecting in my browser and taking a look, this seemed to be the code responsible for the search box
```html
<div id="MSearchBox" class="MSearchBoxInactive">   
      
<span class="left"><img id="MSearchSelect" src="search/mag_sel.png" onmouseover="return searchBox.OnSearchSelectShow()" onmouseout="return searchBox.OnSearchSelectHide()" alt="">           
<input type="text" id="MSearchField" value="Search" accesskey="S" onfocus="searchBox.OnSearchFieldFocus(true)" onblur="searchBox.OnSearchFieldFocus(false)" onkeyup="searchBox.OnSearchFieldChange(event)">         
</span>        

<span class="right">           
<a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""></a>         
</span>       
</div>
```
It seems that the search box has been assigned to a css class that makes it inactive looking at the css class assignment in the first line. 

I am not sure if this is the right place to this issue. Kindly let me know in which case I will reopen it at the right place.

**Comment by zoq** [comment]
Thanks for the report, this is the right place, will look into the issue.

**Comment by rcurtin** [comment]
Yeah, it's a Doxygen script.  Actually I have debugged this one before... let me see if I can quickly refresh my memory and fix it.  I meant to do that back in September, but, well, the time got away from me I guess ...

**Comment by rcurtin** [comment]
(Note also that the website is built with Doxygen 1.8.13, and that is a very specific and intentional decision so that I don't have to go redo all the CSS...)

**Comment by say4n** [comment]
I see. :)

**Comment by rcurtin** [comment]
I'm gonna go ahead and close this, because we are planning on removing the Doxygen documentation, preferring instead Markdown tutorials on Github and other Markdown documentation similar to ensmallen, and then if people really do want to get the super-detailed documentation, they can just look at the source.  (Most of what's available in Doxygen is probably most useful to mlpack developers anyway.)  So, anyway, when that happens, this issue will no longer be an issue because Doxygen is gone.

See [this branch](https://github.com/rcurtin/mlpack/tree/one-include) for the work-in-progress; a PR should be open shortly.
