### ISSUE TITLE
Lack of headers in tutorial pages

### ISSUE THREAD

**Issue by HelioStrike** [mlpack/mlpack.org#5]
On opening a link from the [tutorial page](http://mlpack.org/docs/mlpack-3.0.3/doxygen/nstutorial.html), there seems to be no way to find out what link was clicked from within the page(other than checking the content), due to lack of headers on the top of the pages. While this is not an issue when checking out a single page, it causes a lot of confusion when dealing with multiple tabs.

I looked into the issue further and it looks like there is a header, but its display is set to `None` in Doxygen.css .
```
div.header
{
  display: none;
}
```
/*
I wanted to submit a PR for this but I wasn't sure if I should, as this repo's docs page doesn't seem to contain the latest version's documentation links. Should I have done(/be doing) that? Just curious, I'm not really familiar with github's issue-PR etiquette. :/
*/

**Comment by rcurtin** [comment]
No worries, I can handle this one.  This repository is certainly nowhere near as well-polished as the usual mlpack repository. :)

I think that I originally hid the 'display' block because the formatting can be a bit strange for pages like the class documentation:

http://mlpack.org/docs/mlpack-3.0.3/doxygen/classmlpack_1_1adaboost_1_1AdaBoost.html

But really the issue there has more to do with doxygen's failure to interpret template types in any reasonable way.

Anyway I've made the change and now the headers should be unhidden for the 3.0.3 documentation, and future documentation versions should be built with the header visible also.  Sorry for the inconvenience!  And let me know if there are other issues. :)
